using System;
using System.IO;
using System.Linq;
using System.Net.NetworkInformation;
using System.Text;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using Newtonsoft.Json.Linq;

namespace CursorDesk.App
{
    /// <summary>
    /// Startup license gate. Reads apikey.txt (same folder as exe), which holds a JWT
    /// generated by KeyGen. The JWT payload carries mac / exp / key. The app is only
    /// allowed to run when the MAC matches this machine and the key has not expired.
    /// </summary>
    internal static class LicenseGate
    {
        private static string ApiKeyPath()
        {
            return Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "apikey.txt");
        }

        /// <summary>
        /// Tries to obtain the real API key. Returns false (with error) when the app
        /// must not start. When promptIfMissing is true and apikey.txt is missing/empty,
        /// the user is asked to paste the key and the same validation runs on the input.
        /// </summary>
        public static bool TryGetKey(out string realKey, out string error, bool promptIfMissing)
        {
            realKey = null;
            error = null;

            var path = ApiKeyPath();
            string token = null;

            if (File.Exists(path))
            {
                token = File.ReadAllText(path).Trim();
            }

            if (string.IsNullOrWhiteSpace(token))
            {
                if (!promptIfMissing)
                {
                    error = "未找到 apikey.txt 或内容为空，请输入授权 Key。";
                    return false;
                }

                // Loop: prompt → validate. Re-prompt on invalid input; Cancel exits.
                while (true)
                {
                    token = PromptForToken();
                    if (string.IsNullOrWhiteSpace(token))
                    {
                        error = "已取消输入，程序退出。";
                        return false;
                    }

                    if (ValidateToken(token, out realKey, out error))
                    {
                        try { File.WriteAllText(path, token); }
                        catch { /* best-effort */ }
                        return true;
                    }

                    var retry = MessageBox.Show(
                        error + "\n\n是否重新输入授权 Key？",
                        "授权 Key 无效",
                        MessageBoxButtons.RetryCancel,
                        MessageBoxIcon.Warning);
                    if (retry != DialogResult.Retry)
                    {
                        error = "已取消输入，程序退出。";
                        return false;
                    }
                }
            }

            if (!ValidateToken(token, out realKey, out error))
            {
                return false;
            }

            return true;
        }

        private static string PromptForToken()
        {
            using (var dlg = new InputKeyForm())
            {
                if (dlg.ShowDialog() == DialogResult.OK)
                {
                    return (dlg.Token ?? string.Empty).Trim();
                }
            }
            return null;
        }

        private static bool ValidateToken(string token, out string realKey, out string error)
        {
            realKey = null;
            error = null;

            var parts = token.Split('.');
            if (parts.Length != 3)
            {
                error = "授权 Key 格式错误（不是合法的 JWT）。";
                return false;
            }

            string payloadJson;
            try
            {
                payloadJson = Base64UrlDecode(parts[1]);
            }
            catch
            {
                error = "授权 Key 解析失败。";
                return false;
            }

            JObject payload;
            try
            {
                payload = JObject.Parse(payloadJson);
            }
            catch
            {
                error = "授权 Key 内容损坏。";
                return false;
            }

            var mac = (string)payload["mac"];
            var expToken = payload["exp"];
            var key = (string)payload["key"];

            if (string.IsNullOrWhiteSpace(mac))
            {
                error = "授权 Key 缺少 MAC 信息。";
                return false;
            }
            if (expToken == null || expToken.Type != JTokenType.Integer)
            {
                error = "授权 Key 缺少过期时间。";
                return false;
            }
            if (string.IsNullOrWhiteSpace(key))
            {
                error = "授权 Key 缺少真实 Key。";
                return false;
            }

            // MAC check
            var normMac = NormalizeMac(mac);
            if (normMac == null)
            {
                error = "授权 Key 中的 MAC 格式错误。";
                return false;
            }
            var machineMacs = GetMachineMacs();
            if (!machineMacs.Contains(normMac))
            {
                error = "MAC 地址不匹配，本程序未授权在此设备运行。\n本机 MAC：\n  " +
                        string.Join("\n  ", machineMacs);
                return false;
            }

            // Expiration check
            var exp = expToken.Value<long>();
            var now = (long)(DateTime.UtcNow - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalSeconds;
            if (now > exp)
            {
                var expLocal = DateTimeOffset.FromUnixTimeSeconds(exp).LocalDateTime;
                error = "授权 Key 已过期（过期时间：" + expLocal.ToString("yyyy-MM-dd HH:mm:ss") + "）。";
                return false;
            }

            realKey = key.Trim();
            return true;
        }

        private static string[] GetMachineMacs()
        {
            return NetworkInterface.GetAllNetworkInterfaces()
                .Where(n => n.OperationalStatus == OperationalStatus.Up &&
                            n.NetworkInterfaceType != NetworkInterfaceType.Loopback)
                .Select(n => NormalizeMac(BitConverter.ToString(n.GetPhysicalAddress().GetAddressBytes())))
                .Where(m => m != null)
                .Distinct()
                .ToArray();
        }

        private static string NormalizeMac(string mac)
        {
            if (string.IsNullOrWhiteSpace(mac)) return null;
            var clean = Regex.Replace(mac, @"[^0-9A-Fa-f]", "");
            return clean.Length == 12 ? clean.ToUpper() : null;
        }

        private static string Base64UrlDecode(string input)
        {
            var s = input.Replace('-', '+').Replace('_', '/');
            var pad = s.Length % 4;
            if (pad != 0) s = s.PadRight(s.Length + (4 - pad), '=');
            return Encoding.UTF8.GetString(Convert.FromBase64String(s));
        }
    }
}
